name: deploy

on:
  push:
    branches: [ main ]
    paths:
      - "src/producer_app**"
      - "!src/analytics-consumer/**"

permissions:
    id-token: write
    contents: read 

env: 
    AWS_REGION: ${{ secrets.AWS_REGION }} 
    ECR_REPO: ${{ secrets.ECR_REPO }} 
    CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }} 
    SERVICE_NAME: ${{ secrets.SERVICE_NAME }} 
    CODEDEPLOY_APP: ${{ secrets.CODEDEPLOY_APP }} 
    CODEDEPLOY_GROUP: ${{ secrets.CODEDEPLOY_GROUP }} 

jobs:
  check-infra:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Verify Kafka Exists
        run: |
          cd infra/env/dev
          terraform init -input=false
          terraform output -json > tf.json
          KAFKA=$(jq -r '.kafka_bootstrap.value' tf.json)

          if [ "$KAFKA" = "null" ] || [ -z "$KAFKA" ]; then
            echo "🚨 Kafka not provisioned. Run terraform-apply first."
            exit 1
          fi
                
  deploy:
    needs: check-infra
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Tag Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REPO:$IMAGE_TAG src/producer_app 
          docker tag $ECR_REPO:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Trviy Scan 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $ECR_REPO:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Image to ECR
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:${IMAGE_TAG}
            
      - name: Register New Task Definition
        id: taskdef
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition \
          --task-definition ${CLUSTER_NAME}-task)

          NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq \
          --arg IMAGE "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}" \
          '.taskDefinition
          | del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)
          | .containerDefinitions[0].image = $IMAGE')

          TASK_DEF_ARN=$(echo $NEW_TASK_DEF | aws ecs register-task-definition \
          --cli-input-json file:///dev/stdin \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Replace AppSpec Placeholder
        run: |
          sed -i "s|__TASK_DEF_ARN__|${TASK_DEF_ARN}|g" appspec.yml
            
      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name $CODEDEPLOY_APP \
          --deployment-group-name $CODEDEPLOY_GROUP \
          --revision "revisionType=AppSpecContent,appSpecContent={\"content\":\"$(cat appspec.yml | sed ':a;N;$!ba;s/\n/\\n/g')\"}"
                
        # appSpecContent JSON escapes newlines to avoid CLI fail

