name: deploy-app

on:
  push:
    branches: [ main ]
    paths:
      - "src/producer_app/**"
      - "!src/analytics_consumer/**"

permissions:
  id-token: write
  contents: read 

env: 
  AWS_REGION: ${{ secrets.AWS_REGION }} 
  ECR_REPO: ${{ secrets.ECR_REPO }} 
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }} 
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }} 
  CODEDEPLOY_APP: ${{ secrets.CODEDEPLOY_APP }} 
  CODEDEPLOY_GROUP: ${{ secrets.CODEDEPLOY_GROUP }} 

jobs:
  check-infra:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Test AWS identity
        run: aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3

      - name: Verify Kafka Exists
        run: |
          cd infra/env/dev
          terraform init -input=false
          terraform output -json > tf.json
          KAFKA=$(jq -r '.kafka_bootstrap.value' tf.json)
          if [ "$KAFKA" = "null" ] || [ -z "$KAFKA" ]; then
            echo "🚨 Kafka not provisioned. Run terraform-apply first."
            exit 1
          fi
                
  deploy:
    needs: check-infra
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Tag Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          FULL_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:$IMAGE_TAG"

          docker build -t $FULL_IMAGE -f src/producer_app/Dockerfile . 
          docker push $FULL_IMAGE

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV

      - name: Trivy Scan 
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Image to ECR
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${IMAGE_TAG}
            
      - name: Register New Task Definition
        id: taskdef
        run: |
          TASK_FAMILY="url-shortener-task"
          IMAGE_URI="${{ env.FULL_IMAGE }}"
          
          echo "Fetching current task definition for: $TASK_FAMILY"

          aws ecs describe-task-definition --task-definition $TASK_FAMILY --query 'taskDefinition' > task-def.json

          jq --arg IMAGE "$IMAGE_URI" --arg NAME "ecs-task-definition" '
            del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
            | .containerDefinitions |= map(
                 if .name == $NAME then .image = $IMAGE else . end
              )
          ' task-def.json > clean-task-def.json

          cat clean-task-def.json | grep image

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://clean-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Successfully registered: $TASK_DEF_ARN"

      - name: Replace AppSpec Placeholder
        run: |
          cp src/appspec.yml src/appspec-deploy.yml
          sed -i "s|__TASK_DEF_ARN__|${TASK_DEF_ARN}|g" src/appspec-deploy.yml
            
      - name: Trigger CodeDeploy
        run: |
          APPSPEC_JSON_CONTENT=$(jq -Rs '.' src/appspec-deploy.yml)
          
          echo "{
            \"revisionType\": \"AppSpecContent\",
            \"appSpecContent\": {
              \"content\": $APPSPEC_JSON_CONTENT
            }
          }" > revision.json
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name ${{ env.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ env.CODEDEPLOY_GROUP }} \
            --revision file://revision.json \
            --query 'deploymentID' --output text)
          
          if [ -z "$DEPLOYMENT_ID" ] || [ "$DEPLOYMENT_ID" == "None" ]; then
            echo "❌ Deployment was not created. Exiting."
          fi

          echo "Deployment created: $DEPLOYMENT_ID. Waiting for it to succeed..."

          aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID
          echo "✅ Deployment suceeded"
        # appSpecContent JSON escapes newlines to avoid CLI fail
