name: terraform-plan 

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KAFKA_ASSETS_BUCKET: ${{ secrets.KAFKA_ASSETS_BUCKET }}

jobs:
  plan:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Prepare Kafka Tarball
        run: |
          mkidr -p ../../../assets
          aws s3 cp s3://${{ env.KAFKA_ASSETS_BUCKET }}/kafka_2.13-4.2.0.tgz ../../../assets/
    
      - uses: hashicorp/setup-terraform@v3
            
      - name: Terraform Init & Plan
        run: |
          cd infra/env/dev
          terraform init
          terraform plan 

# Codedeploy will auto handle b/g when the task def changes 